### ISSUE TITLE
Segfault getting maximum_size with SFML 2.6

### ISSUE THREAD

**Issue by dogunbound** [jeremyletang/rust-sfml#307]
main.rs:
```rust
use sfml::graphics::Texture;

fn main() {
    println!("{}", Texture::maximum_size());
}
```
Cargo.toml:
```toml
[package]
name = "test-rust-sfml"
version = "0.1.0"
edition = "2021"

[dependencies.sfml]
git = "https://github.com/jeremyletang/rust-sfml"
features = ["serde"]
```
command:
```
[dogunbound@archlinux test-rust-sfml]$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.00s
     Running `target/debug/test-rust-sfml`
Segmentation fault (core dumped)
```

I'm not completely sure why rust-sfml is segfaulting here for me, but I'll try and figure it out. I just wanted to document it. This is on the latest commit 85ea1d76f117ff33a6d01432c65e482572c7c05e with sfml 2.6.0 installed globally on Arch Linux
